UI changes
airella-system/airella-android-app pull request #7
Opened 2020-10-26 19:30 UTC by jakubdybczak

2020-10-26 23:38 UTC, franczakr requested changes

2020-10-26 23:38 UTC, franczakr commented on app/src/main/java/org/airella/airella/StartActivity.kt
>      override fun onResume() {
Remove unnecessary override

2020-10-26 23:38 UTC, franczakr commented on app/src/main/res/layout/fragment_configuration_succesful.xml
> +            android:id="@+id/imageView2"
Please change id to user-friendly

2020-10-26 23:38 UTC, franczakr commented on app/src/main/java/org/airella/airella/StartActivity.kt
> +    var launched = false
it can be local variable in method onCreate

2020-10-26 23:38 UTC, franczakr commented on app/src/main/java/org/airella/airella/StartActivity.kt
> +                        val intent = Intent(context, MainActivity::class.java)
you should create new Intent using activity context, not application context, use "this" instead ("this@StartActivity" in this example)

2020-10-26 23:38 UTC, franczakr commented on app/src/main/java/org/airella/airella/StartActivity.kt
> +                        val intent = Intent(context, LoginActivity::class.java)
you should create new Intent using activity context, not application context, use "this" instead ("this@StartActivity" in this example)

2020-10-26 23:38 UTC, franczakr commented on app/src/main/java/org/airella/airella/StartActivity.kt
> +                        overridePendingTransition(R.anim.fade_in, R.anim.fade_out)
try to use https://developer.android.com/reference/android/app/Activity#startActivity(android.content.Intent,%20android.os.Bundle) instead, it looks better imo

2020-10-26 23:38 UTC, franczakr commented on app/src/main/java/org/airella/airella/StartActivity.kt
> +                        overridePendingTransition(R.anim.fade_in, R.anim.fade_out)
try to use https://developer.android.com/reference/android/app/Activity#startActivity(android.content.Intent,%20android.os.Bundle) instead, it looks better imo

2020-10-27 23:43 UTC, jakubdybczak commented on app/src/main/java/org/airella/airella/StartActivity.kt
>      override fun onResume() {
I believe that it can't be deleted

2020-10-28 08:36 UTC, franczakr approved these changes

2020-10-28 08:37 UTC, merged